on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test on ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["16", "18", "20"]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js@${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node_version }}
    - name: run test
      run: |
        yarn
        yarn test
